name: Call Packaging Workflow 

on:
    push

jobs:
    call-packaging:
        uses: AntonioFigueiredo/PackagingDebRpm/.github/workflows/packaging.yml@main
        with:
            project_name: cros3
            build_rpm: true
            build_deb: true
            
            deb_matrix: '{"container":["debian:stable","debian:bullseye","debian:unstable","debian:testing"]}'
            rpm_matrix: '{"container":["rockylinux:9"]}'