name: Reusable

on:
    push
  
env:
    RELEASE: unstable
    PROJECT_NAME: cros3

jobs:
  common-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: source_dir

      - name: Get Time
        id: get-time
        run: |
          echo "datetime=$(/bin/date --iso-8601=seconds)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ env.RELEASE }}-ccache-${{ steps.get-time.outputs.datetime }}
          restore-keys: |
            ${{ runner.os }}-${{ env.RELEASE }}-ccache-
            ${{ runner.os }}-ccache-